DEVPREP/config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  root 'sessions#new'
  get '/html' => 'prep_courses#html'
  get '/javascript' => 'prep_courses#javascript'
  get '/git' => 'prep_courses#git'
  get '/ruby' => 'prep_courses#ruby'
  get '/intro'=> 'prep_courses#intro'
  get '/submit' => 'prep_courses#submit'
  get 'users/:id/posts' => 'users#posts', :as => :user_posts
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  post '/posts' => 'posts#create'
  get '/signup'=> 'users#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :posts do
    resources :comments, only: [:create]
  end

  resources :prep_courses, only: [:index]
  resources :users
  resources :likes, only: [:create, :destroy]










end

DEVPREP/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  has_many :comments
  has_attached_file :cover, default_url: "/images/default.jpg"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
  validates :title, length: { maximum: 50 }
  validates :title, :description, :content, presence: true

  def like_count
    self.likes.size
 end
end

DEVPREP/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  # GET /posts
  # GET /posts.json

  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update!(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy!
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :content, :cover)
    end
end

DEVPREP/app/helpers/posts_helper.rb
module PostsHelper
end

DEVPREP/app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :id => "new_blog_form" }) do |f| %>
<div class="form-group">
   <h5>Title</h5>
   <%= f.text_field :title, class: "new-post", :placeholder => "title" %>
   <br></br>
   <h5>Description</h5>
   <%= f.text_field :description, class: "new-post", :placeholder => "Description" %>
   <br></br>
   <h5>Content</h5>
   <%= f.text_area :content, class: "new-post", id: "content-form", :placeholder => "Content" %>
 <a href="https://github.com/vmg/redcarpet/blob/master/README.markdown" target="_blank">Feel free to use HTML here, click for more info.</a>
   <br></br>
   <h5>Cover Photo</h5>
   <%= f.file_field :cover, class: "inputfile" %>
     <%= f.label :cover, "Upload Cover" %>
   <%= f.hidden_field :user_id, :value => @post.user_id %>
   <br></br>
 </div>
   <%= f.submit "Submit Post", class: "btn-submit" %>
<% end %>

DEVPREP/app/views/posts/edit.html.erb
<%= render "prep_courses/header" %>
<!-- Header -->
  <header style="background-image: url('/assets/update2.jpg'); background-size: cover">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <div class="intro-text">
                    <img class="icons8" src="https://cdn3.iconfinder.com/data/icons/technology-mix/200/Technology_Mix_-_Final-37-512.png" width="200" height="200">
                      <span class="name">Edit Your Post</span>
                      <% if @post.user_id == current_user.id %>
                      <h1 class="recipe-delete"><%= link_to "Delete", post_path(@post), method: "delete" %></h2>
                      <% end %>
                  </div>
              </div>
          </div>
      </div>
  </header>

  <!-- WHAT IS devprep -->
  <section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3>Create your post using the form below and click submit.</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <br></br>
                <%= render "posts/form" %>
            </div>
        </div>
    </div>
  </section>

DEVPREP/app/views/posts/index.html.erb
<%= render "prep_courses/header" %>
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header style="background-image: url('https://images.unsplash.com/photo-1433838552652-f9a46b332c40?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&w=1080&fit=max&s=f72ad65c018fe39a7a9898317b0f37dc'); background-size: cover">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>STUDENT HUB</h1>
          <hr class="hub-hr-white">
          <span class="subheading">Information For The Next Generation</span>
        </div>
      </div>
    </div>
  </div>
</header>
<br></br>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <% @posts.reverse.each do |post| %>
      <div class="post-preview">
        <div class="user-container">
          <a href="/users/<%= post.user.id %>"><img id="blog-profile-pic" src="<%= post.user.avatar.url %>"></a>
          <div class="user-box">
            <a id="blog_name" href="/users/<%= post.user.id %>"><%= post.user.first_name %> <%= post.user.last_name %></a>
            <p id="user-info"><%= post.user.title %></p>
          </div>
          <%= render "likes/likes", post: post %>
        </div>
        <%= link_to(post_path(post)) do %>
        <!-- <a href="/posts/<%= post.id %>"> -->
        <h2 class="post-title">
          <%= post.title %>
        </h2>
        <h4 class="post-subtitle">
          <%= post.description %>
        </h4>
        <% end %>
      </div>
      <hr class="hub-hr">
      <% end %>

      <!-- Pager -->
      <ul class="pager">
        <li class="next">
          <a href="#">Older Posts &rarr;</a>
        </li>
      </ul>
    </div>
  </div>
</div>

DEVPREP/app/views/posts/new.html.erb
<%= render "prep_courses/header" %>
<!-- Header -->
  <header style="background-image: url('/assets/update2.jpg'); background-size: cover">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <div class="intro-text">
                    <img class="icons8" src="https://cdn3.iconfinder.com/data/icons/technology-mix/200/Technology_Mix_-_Final-37-512.png" width="200" height="200">
                      <span class="name">Create A New Post</span>
                  </div>
              </div>
          </div>
      </div>
  </header>

  <!-- WHAT IS devprep -->
  <section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3>Create your post using the form below and click submit.</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <br></br>
                <%= render "posts/form" %>
            </div>
        </div>
    </div>
  </section>

DEVPREP/app/views/posts/show.html.erb
<%= render "prep_courses/header" %>

<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('<%= @post.cover.url %>'); background-size: cover">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1><%= @post.title %></h1>
          <h2 class="subheading"><%= @post.description %></h2>
          <hr>
          <span class="meta">Posted by <%= @post.user.first_name %> <%= @post.user.last_name %></span>
          <br></br>
          <% if @post.user_id == current_user.id %>
          <a href="/posts/<%= @post.id %>/edit"><button id="edit-post">Edit Post</button></a>
          <% end %>
          <% if current_user && current_user.admin? %>
          <p class="recipe-delete"><%= link_to "Delete", post_path(@post), method: "delete" %><p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>
<br></br>

<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <%= markdown(@post.content) %>
      </div>
    </div>
  </div>
</article>

<hr>

<!-- Blog Comments -->

<!-- Comments Form -->

<div class="well">
   <h4>Leave a Comment:</h4>
   <%= form_for(:comments, url: post_comments_path(@post), method: :post) do |f| %>
     <%= f.text_area :text, :placeholder => "Such A Great Post...", class: "new-comment" %>
     <%= f.submit "Post", class: "comment-btn-submit" %>
   <% end %>

</div>

<hr>

<!-- Posted Comments -->

<!-- Comment -->
<% @post.comments.each do |comment| %>
<div class="comment-box">
  <a class="pull-left" href="/users/<%= comment.user.id %>">
    <img id="comment-user-photo" class="media-object" src="<%= comment.user.avatar.url %>" alt="http://museprintables.com/images/silhouettes/rubber-duck-silhouette.png">
  </a>
  <div class="media-body">
    <h4 class="media-heading">
      <%= comment.user.first_name %>
      <small><%= comment.created_at %></small>
    </h4>
    <p><%= comment.text %></p>
  </div>
</div>
<hr>
<% end %>


<!-- Nested Comment -->
<!-- <div class="comment-box">
<a class="pull-left" href="#">
<img class="media-object" src="http://placehold.it/64x64" alt="">
</a>
<div class="media-body">
<h4 class="media-heading">Nested Start Bootstrap
<small>August 25, 2014 at 9:30 PM</small>
</h4>
Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
</div>
</div> -->
<!-- End Nested Comment -->
<!-- </div>
</div>
<br></br> -->