DEVPREP/config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  root 'sessions#new'
  get '/html' => 'prep_courses#html'
  get '/javascript' => 'prep_courses#javascript'
  get '/git' => 'prep_courses#git'
  get '/ruby' => 'prep_courses#ruby'
  get '/intro'=> 'prep_courses#intro'
  get '/submit' => 'prep_courses#submit'
  get 'users/:id/posts' => 'users#posts', :as => :user_posts
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  post '/posts' => 'posts#create'
  get '/signup'=> 'users#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :posts do
    resources :comments, only: [:create]
  end

  resources :prep_courses, only: [:index]
  resources :users
  resources :likes, only: [:create, :destroy]










end

DEVPREP/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController


    def new
    end

    def create
      recipients = User.where(id: conversation_params[:recipients])
      conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
      flash[:notice] = "Your message was successfully sent!"
      redirect_to conversation_path(conversation)
    end

    def show
      @receipts = conversation.receipts_for(current_user).order("created_at ASC")
      # mark conversation as read
      conversation.mark_as_read(current_user)
    end


    def reply
      current_user.reply_to_conversation(conversation, message_params[:body])
      flash[:notice] = "Your reply message was successfully sent!"
      redirect_to conversation_path(conversation)
    end

    def trash
      conversation.move_to_trash(current_user)
      redirect_to mailbox_inbox_path
    end

    def untrash
      conversation.untrash(current_user)
      redirect_to mailbox_inbox_path
    end


    private

    def conversation_params
      params.require(:conversation).permit(:subject, :body,recipients:[])
    end

    def message_params
      params.require(:message).permit(:body, :subject)
    end
  end

DEVPREP/app/helpers/conversations_helper.rb
module ConversationsHelper
end

DEVPREP/app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="/users/<%= conversation.originator.id %>">
      <img class="chat_avatar" class="media-object" src="<%= conversation.originator.avatar %>" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.first_name %> <br>
      <a href="/conversations/<%= conversation.id %>">
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
  </a>
  </div>
</div>

DEVPREP/app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients, class: "inbox_labels" %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.first_name, p.last_name, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject, class: "inbox_labels" %>
      <%= f.text_field :subject, placeholder: "Subject", class: "inbox_subject" %>
    </div>
    <div class="form-group">
      <%= f.label :message, class: "inbox_labels" %>
      <%= f.text_area :body, class: 'form-control', placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "send_msg" %>

<% end %>

DEVPREP/app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="chat_avatar" class="media-object" src="<%= message.sender.avatar %>" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.first_name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

DEVPREP/app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

DEVPREP/app/views/conversations/show.html.erb
<%= render "prep_courses/header" %>
<br></br>
<br></br>

<div class="row">
 <div class="col-md-12 text-center">
   <h1> <%= current_user.first_name %>'s INBOX</h1>
 </div>
</div>
<br></br>

<div class="row">
 <div class="spacer"></div>
 <div class="col-md-4">
   <div class="panel panel-default">
     <div class="panel-body">
       <%= render 'mailbox/folders' %>
     </div>
     <div class="spacer"></div>
     <div class="col-md-6 text-center">
       <% if conversation.is_trashed?(current_user) %>
           <%= button_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
       <% else %>
           <%= button_to 'Trash Conversation', trash_conversation_path(conversation), class: 'btn btn-danger', class: 'trash_btn', method: :post,
                       data: {confirm: 'Are you sure?'} %>
       <% end %>
     </div>
   </div>
 </div>

 <div class="col-md-8">
   <div class="panel panel-default">
     <div class="panel-body">
       <%= render partial: 'messages' %>
     </div>
     <div class="panel-footer">
       <!-- Reply Form -->
       <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
           <div class="form-group">
             <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
           </div>
           <%= f.submit "Reply", class: 'btn btn-danger pull-right', class: 'reply_btn' %>
       <% end %>
       <div class="clearfix"></div>
     </div>
   </div>
 </div>
</div>