DEVPREP/config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "example.com"
  root 'sessions#new'
  get '/html' => 'prep_courses#html'
  get '/javascript' => 'prep_courses#javascript'
  get '/git' => 'prep_courses#git'
  get '/ruby' => 'prep_courses#ruby'
  get '/intro'=> 'prep_courses#intro'
  get '/submit' => 'prep_courses#submit'
  get 'users/:id/posts' => 'users#posts', :as => :user_posts
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash
  post '/posts' => 'posts#create'
  get '/signup'=> 'users#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :posts do
    resources :comments, only: [:create]
  end

  resources :prep_courses, only: [:index]
  resources :users
  resources :likes, only: [:create, :destroy]










end

DEVPREP/app/controllers/prep_courses_controller.rb
class PrepCoursesController < ApplicationController
  before_action :set_prep_course, only: [:show, :edit, :update, :destroy]

  # GET /prep_courses
  # GET /prep_courses.json

  def html
  end

  def javascript
  end

  def ruby
  end

  def git
  end

  def login
  end

  def index
    @users = User.all
  end

  def intro
  end

  def prototype
  end

  def submit
  end

  # GET /prep_courses/1
  # GET /prep_courses/1.json
#  def show
#  end
#
#  # GET /prep_courses/new
#  def new
#    @prep_course = PrepCourse.new
#  end
#
#  # GET /prep_courses/1/edit
#  def edit
#  end

  # POST /prep_courses
  # POST /prep_courses.json
#  def create
#    @prep_course = PrepCourse.new(prep_course_params)
#
#    respond_to do |format|
#      if @prep_course.save
#        format.html { redirect_to @prep_course, notice: 'Prep course was successfully created.' }
#        format.json { render :show, status: :created, location: @prep_course }
#      else
#        format.html { render :new }
#        format.json { render json: @prep_course.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # PATCH/PUT /prep_courses/1
  # PATCH/PUT /prep_courses/1.json
#  def update
#    respond_to do |format|
#      if @prep_course.update(prep_course_params)
#        format.html { redirect_to @prep_course, notice: 'Prep course was successfully updated.' }
#        format.json { render :show, status: :ok, location: @prep_course }
#      else
#        format.html { render :edit }
#        format.json { render json: @prep_course.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # DELETE /prep_courses/1
  # DELETE /prep_courses/1.json
#  def destroy
#    @prep_course.destroy
#    respond_to do |format|
#      format.html { redirect_to prep_courses_url, notice: 'Prep course was successfully destroyed.' }
#      format.json { head :no_content }
#    end
#  end

#  private
#    # Use callbacks to share common setup or constraints between actions.
#    def set_prep_course
#      @prep_course = PrepCourse.find(params[:id])
#    end
#
#    # Never trust parameters from the scary internet, only allow the white list through.
#    def prep_course_params
#      params.require(:prep_course).permit(:title, :description, :text)
#    end
end

DEVPREP/app/helpers/prep_courses_helper.rb
module PrepCoursesHelper
end

DEVPREP/app/views/prep_courses/_footer.erb
<!-- Footer -->
<footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-4">
                    <h3>Location</h3>
                    <p>Toronto Canada</p>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col col-md-4">
                    <h3>About DEVprep</h3>
                    <p>DEVprep is a project by students at <a href="http://lighthouselabs.com">Lighthouse Labs</a>.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; DEVprep 2016
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->


<!-- Portfolio Modals -->
<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>Project Title</h2>
                        <hr class="star-primary">
                        <img src="img/portfolio/cabin.png" class="img-responsive img-centered" alt="">
                        <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                        <ul class="list-inline item-details">
                            <li>Client:
                                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                </strong>
                            </li>
                            <li>Date:
                                <strong><a href="http://startbootstrap.com">April 2014</a>
                                </strong>
                            </li>
                            <li>Service:
                                <strong><a href="http://startbootstrap.com">Web Development</a>
                                </strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>Project Title</h2>
                        <hr class="star-primary">
                        <img src="img/portfolio/cake.png" class="img-responsive img-centered" alt="">
                        <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                        <ul class="list-inline item-details">
                            <li>Client:
                                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                </strong>
                            </li>
                            <li>Date:
                                <strong><a href="http://startbootstrap.com">April 2014</a>
                                </strong>
                            </li>
                            <li>Service:
                                <strong><a href="http://startbootstrap.com">Web Development</a>
                                </strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>Project Title</h2>
                        <hr class="star-primary">
                        <img src="img/portfolio/circus.png" class="img-responsive img-centered" alt="">
                        <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                        <ul class="list-inline item-details">
                            <li>Client:
                                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                </strong>
                            </li>
                            <li>Date:
                                <strong><a href="http://startbootstrap.com">April 2014</a>
                                </strong>
                            </li>
                            <li>Service:
                                <strong><a href="http://startbootstrap.com">Web Development</a>
                                </strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>Project Title</h2>
                        <hr class="star-primary">
                        <img src="img/portfolio/game.png" class="img-responsive img-centered" alt="">
                        <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                        <ul class="list-inline item-details">
                            <li>Client:
                                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                </strong>
                            </li>
                            <li>Date:
                                <strong><a href="http://startbootstrap.com">April 2014</a>
                                </strong>
                            </li>
                            <li>Service:
                                <strong><a href="http://startbootstrap.com">Web Development</a>
                                </strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal5" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>Project Title</h2>
                        <hr class="star-primary">
                        <img src="img/portfolio/safe.png" class="img-responsive img-centered" alt="">
                        <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                        <ul class="list-inline item-details">
                            <li>Client:
                                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                </strong>
                            </li>
                            <li>Date:
                                <strong><a href="http://startbootstrap.com">April 2014</a>
                                </strong>
                            </li>
                            <li>Service:
                                <strong><a href="http://startbootstrap.com">Web Development</a>
                                </strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <h2>Project Title</h2>
                        <hr class="star-primary">
                        <img src="img/portfolio/submarine.png" class="img-responsive img-centered" alt="">
                        <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                        <ul class="list-inline item-details">
                            <li>Client:
                                <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                </strong>
                            </li>
                            <li>Date:
                                <strong><a href="http://startbootstrap.com">April 2014</a>
                                </strong>
                            </li>
                            <li>Service:
                                <strong><a href="http://startbootstrap.com">Web Development</a>
                                </strong>
                            </li>
                        </ul>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DEVPREP/app/views/prep_courses/_form.html.erb
<%= form_for(@prep_course) do |f| %>
  <% if @prep_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prep_course.errors.count, "error") %> prohibited this prep_course from being saved:</h2>

      <ul>
      <% @prep_course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

DEVPREP/app/views/prep_courses/_header.html.erb
<nav id="header-opacity"  class="navbar navbar-default navbar-fixed-top">
     <div class="container">
         <!-- Brand and toggle get grouped for better mobile display -->
         <div class="navbar-header page-scroll">
             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                 <span class="sr-only">Toggle navigation</span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="<%= prep_courses_path %>">/DEVprep/</a>
         </div>


         <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
             <ul class="nav navbar-nav navbar-right">
                 <li class="hidden">
                     <a href="#page-top"></a>
                 </li>
                 <li><a href="/mailbox/inbox" class="btn btn-primary btn-lg">
                   <img  id="mail-icon" src="/assets/message.png"/>
                 </a></li>
                 <li><div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">THE HUB<span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li><a href="/posts">HUB INDEX</a></li>
                    <li><a href="/posts/new">CREATE AN ARTICLE</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="http://web-prep.lighthouselabs.ca/" target="_blank">HELP FORUM</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="/submit">SUBMIT WORK</a></li>
                  </ul>
                </div></li>
                 <% if current_user %>
                   <li><div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name.upcase %><span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                      <li><a href="/users/<%= current_user.id %>">VIEW PROFILE</a></li>
                      <li><a href="/users/<%= current_user.id %>/edit">EDIT PROFILE</a></li>
                      <li role="separator" class="divider"></li>
                      <li><a href='/logout'>Logout</a></li>
                    </ul>
                  </div></li>

                 <% else %>
                   <li class="page-scroll">
                     <%= link_to "Signup", 'signup' %>
                   </li>
                   <li class="page-scroll">
                     <%= link_to "Login", '/' %>
                 </li>
             </ul>
                 <% end %>
         </div>
       <!-- navbar-collapse -->
     </div>
     <!--/.container-fluid-->
 </nav>

DEVPREP/app/views/prep_courses/git.html.erb
<%= render "header" %>

<!-- Header -->
  <header id="purple">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <div class="intro-text">
                    <img class="icons8" src="https://cdn1.iconfinder.com/data/icons/logotypes/32/github-128.png" width="110" height="110">
                      <span class="name">GITHUB</span>
                      <span class="skills">Let's get started learning Git & GitHub.</span>
                  </div>
              </div>
          </div>
      </div>
  </header>

  <!-- WHAT IS devprep -->
  <section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>What is Git & GitHub</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <br></br>
                <p>Git is the technology that allows developers to work on projects together. The majour benefit to using Git is version control.</p>
                <br></br>
                <div class="embed-responsive embed-responsive-16by9">
                  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/1h9_cB9mPT8"></iframe>
                </div>
                <br></br>
                <p>Now that we know what Git & GitHub is, let's start by setting up Git on you Mac.</p>
            </div>
        </div>
    </div>
  </section>

  <!-- Objectives Section -->
  <section class="success" id="purple" id="about">
      <div class="container">
          <div class="row">
              <div class="col-lg-12 text-center">
                  <h2>SET-UP</h2>
                  <br></br>
                  <hr class="hub-hr-white">
              </div>
          </div>
          <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
              <br></br>
              <p>The first time set-up of Git on your computer can seem a little bit over whelming, but don't worry it' i's pretty simple.</p>
              <br></br>
              <a href="https://github.com/"><h4 id="git-white">Sign up for Github if you havent already.</h4></a>
              <br></br>
              <a href="https://git-scm.com/download/mac"><h4 id="git-white">Download git.</h4></a>
              <br></br>
              <a href="https://help.github.com/articles/set-up-git/#setting-up-git"><h4 id="git-white">Complete steps 2 through 4 on setting up git.</h4></a>
              <br></br>
              <a href="https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key"><h4 id="git-white">Follow the instruction to generate a new SSH key as well as Adding that SSH key to your github account.</h4></a>
              <br></br>
              <a href="https://help.github.com/articles/setting-your-email-in-git/"><h4 id="git-white">Set up your email so that your not prompted every time.</h4></a>
              <br></br>
              <a href="https://help.github.com/articles/setting-your-username-in-git/"><h4 id="git-white">Set up you username so that your not prompted every time.</h4></a>
              <br></br>
              <p>Now that you have set up your GitHub account and configured Git on you computer let's do a quick lesson.</p>
            </div>
          </div>
      </div>
  </section>

  <!-- More about HTML Section -->
  <section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Git Lessons</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
              <br></br>
              <p>Over at CodeSchool you started learning the basics of JavaScript. Watching the vieos below will help you get a better understanding of how to write HTML and how to code a simple website.</p>
              <br></br>
              <a href="https://www.codeschool.com/courses/try-git"><h3>Complete this course at CodeSchool <i class="fa fa-pencil-square-o"></i></h3></a>
              <br></br>
              <a href="http://rogerdudler.github.io/git-guide/"><h3>Check out this Git walkthrough. It is a great guide. don't forget to bookmark this page. <i class="fa fa-pencil-square-o"></i></h3></a>
              <br></br>
              <p>let's head to the next section where we will watch a few more videos about Git and GitHub.</p>
            </div>
        </div>
    </div>
  </section>

  <!-- Commitment and Expectations Section -->
  <section class="success" id="purple" id="about">
      <div class="container">
          <div class="row">
              <div class="col-lg-12 text-center">
                  <h2>workflows & more</h2>
              </div>
          </div>
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 text-center">
                <br></br>
                <p>Check out this great video about GitHub workflows.</p>
                <div class="embed-responsive embed-responsive-16by9">
                  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/_ALeswWzpBo"></iframe>
                </div>
                <br></br>
                <p>Don't be afraid of the command line, it will make your life much easier.</p>
                <div class="embed-responsive embed-responsive-16by9">
                  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/JPKOESR1k04"></iframe>
                </div>
                <br></br>
                <p>Now that you have a good understanding of git, let's get all of your assignments on git for submission.</p>
              </div>
          </div>
          </div>
      </div>
  </section>

  <!-- ANOTHER More about HTML Section -->
  <section id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2><i class="fa fa-code"></i> Assignment <i class="fa fa-code"></i></h2>
            </div>
        </div>
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 text-center">
            <br></br>
            <p>At this point your assignments should be complete. Create a repo for your recipe assignment that you need to submit.</p>
            <br></br>
            <p>Once you have created your repo on GitHub. Use the command line on your system to clone the repo.</p>
            <p>Move your assignment into your repo folder on your computer.</p>
            <p>Use the command line to now get your files pushed to GitHub. If you cant remember how to do this check out the guide we gave you earlier and watch the video on git command line.</p>
            <a href="/submit" target="_blank" id="blue-button" class="btn btn-lg btn-outline">
                <i class="fa fa-share"></i>SUMIT WORK
            </a>
          </div>
        </div>
    </div>
  </section>

  <!-- Commitment and Expectations Section -->
  <section class="success" id="purple" id="about">
      <div class="container">
          <div class="row">
              <div class="col-lg-12 text-center">
                  <h2>NOW YOU KNOW how to use git and github.</h2>
                  <br></br>
                  <hr class="hub-hr-white">
              </div>
          </div>
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2  text-center">
                  <br></br>
                  <p>Now that you've done the prep course, it would be a great idea to go through each section to make sure you are comfortable with the concept. If you haven't already try to complete all the stretch goals.</p>
              </div>
          </div>
      </div>
  </section>

  <%= render "footer" %>

DEVPREP/app/views/prep_courses/prototype.html.erb
<%= render 'prep_courses/header' %>

<!-- Header -->
<header id="orange">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-text">
                    <span class="name">Create Course</span>
​
                    <span class="skills">Let's create a new course!</span>
                </div>
            </div>
        </div>
    </div>
</header>
​
​
<section id="portfolio">
  <div class="container">
      <div class="row">
          <div class="col-lg-12 text-center">
              <h2>How it works</h2>
          </div>
      </div>
      <div class="row">
          <div class="col-lg-8 col-lg-offset-2 text-center">
              <br></br>
              <p>Simply fill out the form below and follow the instructions to build a brand new course.</p>
          </div>
      </div>
  </div>
</section>
​
<section id="section_block_padding" id="orange" class="success" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>The Basics</h2>
            </div>
        </div>
        <div id="content_container" class="row">
          <div class="col-lg-8 col-lg-offset-2 text-center">
            <br></br>
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">Course Name</span>
              <input type="text" class="form-control" aria-describedby="basic-addon1">
            </div>
            <br></br>
            <div class="input-group">
              <span class="input-group-addon" id="basic-addon1">subject</span>
              <input type="text" class="form-control" aria-describedby="basic-addon1">
            </div>
            <!-- JS INSERT GOES HERE -->
            </div>
        </div>
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 text-center">
          <button id="add_section" class="btn btn-lg btn-outline">
              <i class="fa fa-plus"></i> Section
          </button>
          <br></br>
        </div>
      </div>
    </div>
</section>
<br></br>
​